// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The AttachedClusters API provides a single centrally managed service
/// to register and manage Anthos attached clusters that run on customer's owned
/// infrastructure.
///
/// @Snippet(path: "AttachedClustersQuickstart")
public class AttachedClustersClient: Clients.AttachedClustersProtocol {
  let inner: any Clients.AttachedClustersStub

  /// Creates a new `AttachedClustersClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AttachedClustersStub = try Clients.AttachedClustersTransport(options)
    inner = Clients.AttachedClustersRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AttachedClustersLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_CreateAttachedCluster")
  public func createAttachedCluster(
    request: CreateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAttachedCluster(request: request, options: options)
  }

  /// Creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_CreateAttachedCluster")
  public func createAttachedCluster(
    withPolling: CreateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try AttachedCluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createAttachedCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates an
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_UpdateAttachedCluster")
  public func updateAttachedCluster(
    request: UpdateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAttachedCluster(request: request, options: options)
  }

  /// Updates an
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_UpdateAttachedCluster")
  public func updateAttachedCluster(
    withPolling: UpdateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try AttachedCluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateAttachedCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Imports creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// by importing an existing Fleet Membership resource.
  ///
  /// Attached Clusters created before the introduction of the Anthos Multi-Cloud
  /// API can be imported through this method.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_ImportAttachedCluster")
  public func importAttachedCluster(
    request: ImportAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.importAttachedCluster(request: request, options: options)
  }

  /// Imports creates a new
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// by importing an existing Fleet Membership resource.
  ///
  /// Attached Clusters created before the introduction of the Anthos Multi-Cloud
  /// API can be imported through this method.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_ImportAttachedCluster")
  public func importAttachedCluster(
    withPolling: ImportAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try AttachedCluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.importAttachedCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Describes a specific
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_GetAttachedCluster")
  public func getAttachedCluster(
    request: GetAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster {
    try await self.inner.getAttachedCluster(request: request, options: options)
  }

  /// Lists all [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_ListAttachedClusters")
  public func listAttachedClusters(
    request: ListAttachedClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse {
    try await self.inner.listAttachedClusters(request: request, options: options)
  }

  /// Lists all [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster]
  /// resources on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  ///
  /// @Snippet(path: "AttachedClusters_ListAttachedClusters")
  public func listAttachedClusters(
    byItem: ListAttachedClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AttachedCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listAttachedClusters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deletes a specific
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_DeleteAttachedCluster")
  public func deleteAttachedCluster(
    request: DeleteAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAttachedCluster(request: request, options: options)
  }

  /// Deletes a specific
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AttachedClusters_DeleteAttachedCluster")
  public func deleteAttachedCluster(
    withPolling: DeleteAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteAttachedCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Returns information, such as supported Kubernetes versions, on a given
  /// Google Cloud location.
  ///
  /// @Snippet(path: "AttachedClusters_GetAttachedServerConfig")
  public func getAttachedServerConfig(
    request: GetAttachedServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig {
    try await self.inner.getAttachedServerConfig(request: request, options: options)
  }

  /// Generates the install manifest to be installed on the target cluster.
  ///
  /// @Snippet(path: "AttachedClusters_GenerateAttachedClusterInstallManifest")
  public func generateAttachedClusterInstallManifest(
    request: GenerateAttachedClusterInstallManifestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    try await self.inner.generateAttachedClusterInstallManifest(request: request, options: options)
  }

  /// Generates an access token for a cluster agent.
  ///
  /// @Snippet(path: "AttachedClusters_GenerateAttachedClusterAgentToken")
  public func generateAttachedClusterAgentToken(
    request: GenerateAttachedClusterAgentTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse {
    try await self.inner.generateAttachedClusterAgentToken(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AttachedClusters_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AttachedClusters_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AttachedClusters_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AttachedClusters_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AttachedClusters_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AttachedClustersClient`.
  ///
  /// To mock `AttachedClustersClient` change your functions to receive
  /// `some AttachedClustersProtocol` or `any AttachedClustersProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AttachedClustersProtocol {
    /// See `AttachedClustersClient.createAttachedCluster`.
    func createAttachedCluster(request: CreateAttachedClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.createAttachedCluster`.
    func createAttachedCluster(withPolling: CreateAttachedClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.createAttachedCluster`.
    func createAttachedCluster(
      parent: Swift.String,
      attachedCluster: AttachedCluster?,
      attachedClusterId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.updateAttachedCluster`.
    func updateAttachedCluster(request: UpdateAttachedClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.updateAttachedCluster`.
    func updateAttachedCluster(withPolling: UpdateAttachedClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.updateAttachedCluster`.
    func updateAttachedCluster(
      attachedCluster: AttachedCluster?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.importAttachedCluster`.
    func importAttachedCluster(request: ImportAttachedClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.importAttachedCluster`.
    func importAttachedCluster(withPolling: ImportAttachedClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.importAttachedCluster`.
    func importAttachedCluster(
      parent: Swift.String,
      fleetMembership: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.getAttachedCluster`.
    func getAttachedCluster(request: GetAttachedClusterRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.AttachedCluster

    /// See `AttachedClustersClient.getAttachedCluster`.
    func getAttachedCluster(
      name: Swift.String,
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster

    /// See `AttachedClustersClient.listAttachedClusters`.
    func listAttachedClusters(request: ListAttachedClustersRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse

    /// See `AttachedClustersClient.listAttachedClusters`.
    func listAttachedClusters(
      byItem: ListAttachedClustersRequest
    ) throws -> any AsyncSequence<AttachedCluster, Swift.Error>

    /// See `AttachedClustersClient.listAttachedClusters`.
    func listAttachedClusters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AttachedCluster, Swift.Error>

    /// See `AttachedClustersClient.deleteAttachedCluster`.
    func deleteAttachedCluster(request: DeleteAttachedClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.deleteAttachedCluster`.
    func deleteAttachedCluster(withPolling: DeleteAttachedClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Void>

    /// See `AttachedClustersClient.deleteAttachedCluster`.
    func deleteAttachedCluster(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `AttachedClustersClient.getAttachedServerConfig`.
    func getAttachedServerConfig(request: GetAttachedServerConfigRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig

    /// See `AttachedClustersClient.getAttachedServerConfig`.
    func getAttachedServerConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig

    /// See `AttachedClustersClient.generateAttachedClusterInstallManifest`.
    func generateAttachedClusterInstallManifest(
      request: GenerateAttachedClusterInstallManifestRequest
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse

    /// See `AttachedClustersClient.generateAttachedClusterInstallManifest`.
    func generateAttachedClusterInstallManifest(
      parent: Swift.String,
      attachedClusterId: Swift.String,
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse

    /// See `AttachedClustersClient.generateAttachedClusterAgentToken`.
    func generateAttachedClusterAgentToken(request: GenerateAttachedClusterAgentTokenRequest)
      async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse

    /// See `AttachedClustersClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AttachedClustersClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AttachedClustersClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AttachedClustersClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `AttachedClustersClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AttachedClustersClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `AttachedClustersClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AttachedClustersClient.createAttachedCluster`.
    func createAttachedCluster(
      request: CreateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.createAttachedCluster`.
    func createAttachedCluster(
      withPolling: CreateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.updateAttachedCluster`.
    func updateAttachedCluster(
      request: UpdateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.updateAttachedCluster`.
    func updateAttachedCluster(
      withPolling: UpdateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.importAttachedCluster`.
    func importAttachedCluster(
      request: ImportAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.importAttachedCluster`.
    func importAttachedCluster(
      withPolling: ImportAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster>

    /// See `AttachedClustersClient.getAttachedCluster`.
    func getAttachedCluster(
      request: GetAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster

    /// See `AttachedClustersClient.listAttachedClusters`.
    func listAttachedClusters(
      request: ListAttachedClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse

    /// See `AttachedClustersClient.listAttachedClusters`.
    func listAttachedClusters(
      byItem: ListAttachedClustersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AttachedCluster, Swift.Error>

    /// See `AttachedClustersClient.deleteAttachedCluster`.
    func deleteAttachedCluster(
      request: DeleteAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AttachedClustersClient.deleteAttachedCluster`.
    func deleteAttachedCluster(
      withPolling: DeleteAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `AttachedClustersClient.getAttachedServerConfig`.
    func getAttachedServerConfig(
      request: GetAttachedServerConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig

    /// See `AttachedClustersClient.generateAttachedClusterInstallManifest`.
    func generateAttachedClusterInstallManifest(
      request: GenerateAttachedClusterInstallManifestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse

    /// See `AttachedClustersClient.generateAttachedClusterAgentToken`.
    func generateAttachedClusterAgentToken(
      request: GenerateAttachedClusterAgentTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse

    /// See `AttachedClustersClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AttachedClustersClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AttachedClustersClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AttachedClustersClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AttachedClustersProtocol {
  public func createAttachedCluster(request: CreateAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAttachedCluster(request: request, options: .init())
  }

  public func createAttachedCluster(
    request: CreateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAttachedCluster(withPolling: CreateAttachedClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AttachedCluster>
  {
    try await self.createAttachedCluster(withPolling: withPolling, options: .init())
  }

  public func createAttachedCluster(
    withPolling: CreateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAttachedCluster(
    parent: Swift.String,
    attachedCluster: AttachedCluster?,
    attachedClusterId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let request = CreateAttachedClusterRequest().with {
      $0.parent = parent
      $0.attachedCluster = attachedCluster
      $0.attachedClusterId = attachedClusterId
    }
    return try await self.createAttachedCluster(withPolling: request)
  }

  public func updateAttachedCluster(request: UpdateAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAttachedCluster(request: request, options: .init())
  }

  public func updateAttachedCluster(
    request: UpdateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateAttachedCluster(withPolling: UpdateAttachedClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AttachedCluster>
  {
    try await self.updateAttachedCluster(withPolling: withPolling, options: .init())
  }

  public func updateAttachedCluster(
    withPolling: UpdateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAttachedCluster(
    attachedCluster: AttachedCluster?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let request = UpdateAttachedClusterRequest().with {
      $0.attachedCluster = attachedCluster
      $0.updateMask = updateMask
    }
    return try await self.updateAttachedCluster(withPolling: request)
  }

  public func importAttachedCluster(request: ImportAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.importAttachedCluster(request: request, options: .init())
  }

  public func importAttachedCluster(
    request: ImportAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func importAttachedCluster(withPolling: ImportAttachedClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AttachedCluster>
  {
    try await self.importAttachedCluster(withPolling: withPolling, options: .init())
  }

  public func importAttachedCluster(
    withPolling: ImportAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AttachedCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func importAttachedCluster(
    parent: Swift.String,
    fleetMembership: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AttachedCluster> {
    let request = ImportAttachedClusterRequest().with {
      $0.parent = parent
      $0.fleetMembership = fleetMembership
    }
    return try await self.importAttachedCluster(withPolling: request)
  }

  public func getAttachedCluster(request: GetAttachedClusterRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AttachedCluster
  {
    try await self.getAttachedCluster(request: request, options: .init())
  }

  public func getAttachedCluster(
    request: GetAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAttachedCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster {
    let request = GetAttachedClusterRequest().with {
      $0.name = name
    }
    return try await self.getAttachedCluster(request: request)
  }

  public func listAttachedClusters(request: ListAttachedClustersRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse
  {
    try await self.listAttachedClusters(request: request, options: .init())
  }

  public func listAttachedClusters(
    request: ListAttachedClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAttachedClusters(
    byItem: ListAttachedClustersRequest
  ) throws -> any AsyncSequence<AttachedCluster, Swift.Error> {
    try self.listAttachedClusters(byItem: byItem, options: .init())
  }

  public func listAttachedClusters(
    byItem: ListAttachedClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AttachedCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAttachedClusters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AttachedCluster, Swift.Error> {
    let request = ListAttachedClustersRequest().with {
      $0.parent = parent
    }
    return try self.listAttachedClusters(byItem: request)
  }

  public func deleteAttachedCluster(request: DeleteAttachedClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAttachedCluster(request: request, options: .init())
  }

  public func deleteAttachedCluster(
    request: DeleteAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteAttachedCluster(withPolling: DeleteAttachedClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteAttachedCluster(withPolling: withPolling, options: .init())
  }

  public func deleteAttachedCluster(
    withPolling: DeleteAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAttachedCluster(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteAttachedClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteAttachedCluster(withPolling: request)
  }

  public func getAttachedServerConfig(request: GetAttachedServerConfigRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig
  {
    try await self.getAttachedServerConfig(request: request, options: .init())
  }

  public func getAttachedServerConfig(
    request: GetAttachedServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAttachedServerConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig {
    let request = GetAttachedServerConfigRequest().with {
      $0.name = name
    }
    return try await self.getAttachedServerConfig(request: request)
  }

  public func generateAttachedClusterInstallManifest(
    request: GenerateAttachedClusterInstallManifestRequest
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    try await self.generateAttachedClusterInstallManifest(request: request, options: .init())
  }

  public func generateAttachedClusterInstallManifest(
    request: GenerateAttachedClusterInstallManifestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateAttachedClusterInstallManifest(
    parent: Swift.String,
    attachedClusterId: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
    let request = GenerateAttachedClusterInstallManifestRequest().with {
      $0.parent = parent
      $0.attachedClusterId = attachedClusterId
    }
    return try await self.generateAttachedClusterInstallManifest(request: request)
  }

  public func generateAttachedClusterAgentToken(request: GenerateAttachedClusterAgentTokenRequest)
    async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse
  {
    try await self.generateAttachedClusterAgentToken(request: request, options: .init())
  }

  public func generateAttachedClusterAgentToken(
    request: GenerateAttachedClusterAgentTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
