// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class AttachedClustersLogging: AttachedClustersStub {
    let inner: any AttachedClustersStub
    let logger: Logger

    public init(_ inner: any AttachedClustersStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-gkemulticloud-v1"
      logger[metadataKey: "gcp.client.service"] = "gkemulticloud"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AttachedClusters"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createAttachedCluster(
      request: CreateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAttachedCluster",
        action: {
          (r: CreateAttachedClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.createAttachedCluster(request: r, options: o)
        })
    }

    public func updateAttachedCluster(
      request: UpdateAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAttachedCluster",
        action: {
          (r: UpdateAttachedClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.updateAttachedCluster(request: r, options: o)
        })
    }

    public func importAttachedCluster(
      request: ImportAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importAttachedCluster",
        action: {
          (r: ImportAttachedClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.importAttachedCluster(request: r, options: o)
        })
    }

    public func getAttachedCluster(
      request: GetAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedCluster {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAttachedCluster",
        action: {
          (r: GetAttachedClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEMultiCloudV1.AttachedCluster
          in
          return try await self.inner.getAttachedCluster(request: r, options: o)
        })
    }

    public func listAttachedClusters(
      request: ListAttachedClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAttachedClusters",
        action: {
          (r: ListAttachedClustersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEMultiCloudV1.ListAttachedClustersResponse
          in
          return try await self.inner.listAttachedClusters(request: r, options: o)
        })
    }

    public func deleteAttachedCluster(
      request: DeleteAttachedClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAttachedCluster",
        action: {
          (r: DeleteAttachedClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.deleteAttachedCluster(request: r, options: o)
        })
    }

    public func getAttachedServerConfig(
      request: GetAttachedServerConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAttachedServerConfig",
        action: {
          (r: GetAttachedServerConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGKEMultiCloudV1.AttachedServerConfig
          in
          return try await self.inner.getAttachedServerConfig(request: r, options: o)
        })
    }

    public func generateAttachedClusterInstallManifest(
      request: GenerateAttachedClusterInstallManifestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateAttachedClusterInstallManifest",
        action: {
          (r: GenerateAttachedClusterInstallManifestRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterInstallManifestResponse
          in
          return try await self.inner.generateAttachedClusterInstallManifest(request: r, options: o)
        })
    }

    public func generateAttachedClusterAgentToken(
      request: GenerateAttachedClusterAgentTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateAttachedClusterAgentToken",
        action: {
          (r: GenerateAttachedClusterAgentTokenRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudGKEMultiCloudV1.GenerateAttachedClusterAgentTokenResponse
          in
          return try await self.inner.generateAttachedClusterAgentToken(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongrunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
