// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Information about a supported Attached Clusters platform version.
public struct AttachedPlatformVersionInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Platform version name.
  public var version: Swift.String = Swift.String()

  /// Optional. True if the version is available for attachedcluster creation. If
  /// a version is enabled, it can be used to attach new clusters.
  public var enabled: Swift.Bool = Swift.Bool()

  /// Optional. True if this cluster version belongs to a minor version that has
  /// reached its end of life and is no longer in scope to receive security and
  /// bug fixes.
  public var endOfLife: Swift.Bool = Swift.Bool()

  /// Optional. The estimated date (in Pacific Time) when this cluster version
  /// will reach its end of life. Or if this version is no longer supported (the
  /// `end_of_life` field is true), this is the actual date (in Pacific time)
  /// when the version reached its end of life.
  public var endOfLifeDate: GoogleType.Date? = nil

  /// Optional. The date (in Pacific Time) when the cluster version was released.
  public var releaseDate: GoogleType.Date? = nil

  /// Initialize a new instance of `AttachedPlatformVersionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttachedPlatformVersionInfo().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AttachedPlatformVersionInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
