// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Configuration related to CloudWatch metrics collection in an AWS
/// Auto Scaling group.
@available(*, deprecated)
public struct AwsAutoscalingGroupMetricsCollection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The frequency at which EC2 Auto Scaling sends aggregated data to
  /// AWS CloudWatch. The only valid value is "1Minute".
  public var granularity: Swift.String = Swift.String()

  /// Optional. The metrics to enable. For a list of valid metrics, see
  /// https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_EnableMetricsCollection.html.
  /// If you specify Granularity and don't specify any metrics, all metrics are
  /// enabled.
  public var metrics: [Swift.String] = []

  /// Initialize a new instance of `AwsAutoscalingGroupMetricsCollection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AwsAutoscalingGroupMetricsCollection().with { $0.granularity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AwsAutoscalingGroupMetricsCollection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
