// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The AwsClusters API provides a single centrally managed service
/// to create and manage Anthos clusters that run on AWS infrastructure.
///
/// @Snippet(path: "AwsClustersQuickstart")
@available(*, deprecated)
public final class AwsClustersClient: Clients.AwsClustersProtocol, Sendable {
  let inner: any Clients.AwsClustersStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `AwsClustersClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AwsClustersStub = try Clients.AwsClustersTransport(options)
    inner = Clients.AwsClustersRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AwsClustersLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster]
  /// resource on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_CreateAwsCluster")
  @available(*, deprecated)
  public func createAwsCluster(
    request: CreateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAwsCluster(request: request, options: options)
  }

  /// Creates a new [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster]
  /// resource on a given Google Cloud Platform project and region.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_CreateAwsCluster")
  @available(*, deprecated)
  public func createAwsCluster(
    withPolling: CreateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AwsCluster>.State in
      return try op._extractStatus(AwsCluster.self)
    }
    let rawOp = try await self.createAwsCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  ///
  /// @Snippet(path: "AwsClusters_UpdateAwsCluster")
  @available(*, deprecated)
  public func updateAwsCluster(
    request: UpdateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAwsCluster(request: request, options: options)
  }

  /// Updates an [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  ///
  /// @Snippet(path: "AwsClusters_UpdateAwsCluster")
  @available(*, deprecated)
  public func updateAwsCluster(
    withPolling: UpdateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AwsCluster>.State in
      return try op._extractStatus(AwsCluster.self)
    }
    let rawOp = try await self.updateAwsCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Describes a specific [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster]
  /// resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  ///
  /// @Snippet(path: "AwsClusters_GetAwsCluster")
  @available(*, deprecated)
  public func getAwsCluster(
    request: GetAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsCluster {
    try await self.inner.getAwsCluster(request: request, options: options)
  }

  /// Lists all [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster] resources
  /// on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  ///
  /// @Snippet(path: "AwsClusters_ListAwsClusters")
  @available(*, deprecated)
  public func listAwsClusters(
    request: ListAwsClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsClustersResponse {
    try await self.inner.listAwsClusters(request: request, options: options)
  }

  /// Lists all [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster] resources
  /// on a given Google Cloud project and region.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  ///
  /// @Snippet(path: "AwsClusters_ListAwsClusters")
  @available(*, deprecated)
  public func listAwsClusters(
    byItem: ListAwsClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AwsCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsClustersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAwsClusters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deletes a specific [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster]
  /// resource.
  ///
  /// Fails if the cluster has one or more associated
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] resources.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_DeleteAwsCluster")
  @available(*, deprecated)
  public func deleteAwsCluster(
    request: DeleteAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAwsCluster(request: request, options: options)
  }

  /// Deletes a specific [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster]
  /// resource.
  ///
  /// Fails if the cluster has one or more associated
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] resources.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_DeleteAwsCluster")
  @available(*, deprecated)
  public func deleteAwsCluster(
    withPolling: DeleteAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAwsCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Generates an access token for a cluster agent.
  ///
  /// @Snippet(path: "AwsClusters_GenerateAwsClusterAgentToken")
  @available(*, deprecated)
  public func generateAwsClusterAgentToken(
    request: GenerateAwsClusterAgentTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAwsClusterAgentTokenResponse {
    try await self.inner.generateAwsClusterAgentToken(request: request, options: options)
  }

  /// Generates a short-lived access token to authenticate to a given
  /// [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  ///
  /// @Snippet(path: "AwsClusters_GenerateAwsAccessToken")
  @available(*, deprecated)
  public func generateAwsAccessToken(
    request: GenerateAwsAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAwsAccessTokenResponse {
    try await self.inner.generateAwsAccessToken(request: request, options: options)
  }

  /// Creates a new [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool],
  /// attached to a given [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster].
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_CreateAwsNodePool")
  @available(*, deprecated)
  public func createAwsNodePool(
    request: CreateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAwsNodePool(request: request, options: options)
  }

  /// Creates a new [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool],
  /// attached to a given [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster].
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_CreateAwsNodePool")
  @available(*, deprecated)
  public func createAwsNodePool(
    withPolling: CreateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      return try op._extractStatus(AwsNodePool.self)
    }
    let rawOp = try await self.createAwsNodePool(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool].
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  ///
  /// @Snippet(path: "AwsClusters_UpdateAwsNodePool")
  @available(*, deprecated)
  public func updateAwsNodePool(
    request: UpdateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAwsNodePool(request: request, options: options)
  }

  /// Updates an [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool].
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  ///
  /// @Snippet(path: "AwsClusters_UpdateAwsNodePool")
  @available(*, deprecated)
  public func updateAwsNodePool(
    withPolling: UpdateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      return try op._extractStatus(AwsNodePool.self)
    }
    let rawOp = try await self.updateAwsNodePool(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Rolls back a previously aborted or failed
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] update request.
  /// Makes no changes if the last update request successfully finished.
  /// If an update request is in progress, you cannot rollback the update.
  /// You must first cancel or let it finish unsuccessfully before you can
  /// rollback.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  ///
  /// @Snippet(path: "AwsClusters_RollbackAwsNodePoolUpdate")
  @available(*, deprecated)
  public func rollbackAwsNodePoolUpdate(
    request: RollbackAwsNodePoolUpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rollbackAwsNodePoolUpdate(request: request, options: options)
  }

  /// Rolls back a previously aborted or failed
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] update request.
  /// Makes no changes if the last update request successfully finished.
  /// If an update request is in progress, you cannot rollback the update.
  /// You must first cancel or let it finish unsuccessfully before you can
  /// rollback.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  ///
  /// @Snippet(path: "AwsClusters_RollbackAwsNodePoolUpdate")
  @available(*, deprecated)
  public func rollbackAwsNodePoolUpdate(
    withPolling: RollbackAwsNodePoolUpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      return try op._extractStatus(AwsNodePool.self)
    }
    let rawOp = try await self.rollbackAwsNodePoolUpdate(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Describes a specific
  /// [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool] resource.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  ///
  /// @Snippet(path: "AwsClusters_GetAwsNodePool")
  @available(*, deprecated)
  public func getAwsNodePool(
    request: GetAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsNodePool {
    try await self.inner.getAwsNodePool(request: request, options: options)
  }

  /// Lists all [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool]
  /// resources on a given
  /// [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  ///
  /// @Snippet(path: "AwsClusters_ListAwsNodePools")
  @available(*, deprecated)
  public func listAwsNodePools(
    request: ListAwsNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsNodePoolsResponse {
    try await self.inner.listAwsNodePools(request: request, options: options)
  }

  /// Lists all [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool]
  /// resources on a given
  /// [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster].
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  ///
  /// @Snippet(path: "AwsClusters_ListAwsNodePools")
  @available(*, deprecated)
  public func listAwsNodePools(
    byItem: ListAwsNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AwsNodePool, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsNodePoolsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAwsNodePools(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deletes a specific [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool]
  /// resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_DeleteAwsNodePool")
  @available(*, deprecated)
  public func deleteAwsNodePool(
    request: DeleteAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAwsNodePool(request: request, options: options)
  }

  /// Deletes a specific [AwsNodePool][google.cloud.gkemulticloud.v1.AwsNodePool]
  /// resource.
  ///
  /// If successful, the response contains a newly created
  /// [Operation][google.longrunning.Operation] resource that can be
  /// described to track the status of the operation.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsNodePool]: <doc:AwsNodePool>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AwsClusters_DeleteAwsNodePool")
  @available(*, deprecated)
  public func deleteAwsNodePool(
    withPolling: DeleteAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAwsNodePool(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets the OIDC discovery document for the cluster.
  /// See the
  /// [OpenID Connect Discovery 1.0
  /// specification](https://openid.net/specs/openid-connect-discovery-1_0.html)
  /// for details.
  ///
  /// @Snippet(path: "AwsClusters_GetAwsOpenIdConfig")
  @available(*, deprecated)
  public func getAwsOpenIdConfig(
    request: GetAwsOpenIdConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsOpenIdConfig {
    try await self.inner.getAwsOpenIdConfig(request: request, options: options)
  }

  /// Gets the public component of the cluster signing keys in
  /// JSON Web Key format.
  ///
  /// @Snippet(path: "AwsClusters_GetAwsJsonWebKeys")
  @available(*, deprecated)
  public func getAwsJsonWebKeys(
    request: GetAwsJsonWebKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsJsonWebKeys {
    try await self.inner.getAwsJsonWebKeys(request: request, options: options)
  }

  /// Returns information, such as supported AWS regions and Kubernetes
  /// versions, on a given Google Cloud location.
  ///
  /// @Snippet(path: "AwsClusters_GetAwsServerConfig")
  @available(*, deprecated)
  public func getAwsServerConfig(
    request: GetAwsServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsServerConfig {
    try await self.inner.getAwsServerConfig(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AwsClusters_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AwsClusters_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AwsClusters_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AwsClusters_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AwsClusters_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AwsClustersClient`.
  ///
  /// To mock `AwsClustersClient` change your functions to receive
  /// `some AwsClustersProtocol` or `any AwsClustersProtocol`
  /// and pass a mock implementation in your tests.
  @available(*, deprecated)
  public protocol AwsClustersProtocol {
    /// See `AwsClustersClient.createAwsCluster`.
    @available(*, deprecated)
    func createAwsCluster(request: CreateAwsClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.createAwsCluster`.
    @available(*, deprecated)
    func createAwsCluster(withPolling: CreateAwsClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<AwsCluster>

    /// See `AwsClustersClient.createAwsCluster`.
    @available(*, deprecated)
    func createAwsCluster(
      parent: Swift.String,
      awsCluster: AwsCluster?,
      awsClusterId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster>

    /// See `AwsClustersClient.updateAwsCluster`.
    @available(*, deprecated)
    func updateAwsCluster(request: UpdateAwsClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.updateAwsCluster`.
    @available(*, deprecated)
    func updateAwsCluster(withPolling: UpdateAwsClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<AwsCluster>

    /// See `AwsClustersClient.updateAwsCluster`.
    @available(*, deprecated)
    func updateAwsCluster(
      awsCluster: AwsCluster?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster>

    /// See `AwsClustersClient.getAwsCluster`.
    @available(*, deprecated)
    func getAwsCluster(request: GetAwsClusterRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.AwsCluster

    /// See `AwsClustersClient.getAwsCluster`.
    @available(*, deprecated)
    func getAwsCluster(
      name: Swift.String,
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsCluster

    /// See `AwsClustersClient.listAwsClusters`.
    @available(*, deprecated)
    func listAwsClusters(request: ListAwsClustersRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.ListAwsClustersResponse

    /// See `AwsClustersClient.listAwsClusters`.
    @available(*, deprecated)
    func listAwsClusters(
      byItem: ListAwsClustersRequest
    ) throws -> any AsyncSequence<AwsCluster, Swift.Error>

    /// See `AwsClustersClient.listAwsClusters`.
    @available(*, deprecated)
    func listAwsClusters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AwsCluster, Swift.Error>

    /// See `AwsClustersClient.deleteAwsCluster`.
    @available(*, deprecated)
    func deleteAwsCluster(request: DeleteAwsClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.deleteAwsCluster`.
    @available(*, deprecated)
    func deleteAwsCluster(withPolling: DeleteAwsClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `AwsClustersClient.deleteAwsCluster`.
    @available(*, deprecated)
    func deleteAwsCluster(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AwsClustersClient.generateAwsClusterAgentToken`.
    @available(*, deprecated)
    func generateAwsClusterAgentToken(request: GenerateAwsClusterAgentTokenRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.GenerateAwsClusterAgentTokenResponse

    /// See `AwsClustersClient.generateAwsAccessToken`.
    @available(*, deprecated)
    func generateAwsAccessToken(request: GenerateAwsAccessTokenRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.GenerateAwsAccessTokenResponse

    /// See `AwsClustersClient.createAwsNodePool`.
    @available(*, deprecated)
    func createAwsNodePool(request: CreateAwsNodePoolRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.createAwsNodePool`.
    @available(*, deprecated)
    func createAwsNodePool(withPolling: CreateAwsNodePoolRequest) async throws -> any GoogleCloudGax
      .PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.createAwsNodePool`.
    @available(*, deprecated)
    func createAwsNodePool(
      parent: Swift.String,
      awsNodePool: AwsNodePool?,
      awsNodePoolId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.updateAwsNodePool`.
    @available(*, deprecated)
    func updateAwsNodePool(request: UpdateAwsNodePoolRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.updateAwsNodePool`.
    @available(*, deprecated)
    func updateAwsNodePool(withPolling: UpdateAwsNodePoolRequest) async throws -> any GoogleCloudGax
      .PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.updateAwsNodePool`.
    @available(*, deprecated)
    func updateAwsNodePool(
      awsNodePool: AwsNodePool?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.rollbackAwsNodePoolUpdate`.
    @available(*, deprecated)
    func rollbackAwsNodePoolUpdate(request: RollbackAwsNodePoolUpdateRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.rollbackAwsNodePoolUpdate`.
    @available(*, deprecated)
    func rollbackAwsNodePoolUpdate(withPolling: RollbackAwsNodePoolUpdateRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.rollbackAwsNodePoolUpdate`.
    @available(*, deprecated)
    func rollbackAwsNodePoolUpdate(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.getAwsNodePool`.
    @available(*, deprecated)
    func getAwsNodePool(request: GetAwsNodePoolRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.AwsNodePool

    /// See `AwsClustersClient.getAwsNodePool`.
    @available(*, deprecated)
    func getAwsNodePool(
      name: Swift.String,
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsNodePool

    /// See `AwsClustersClient.listAwsNodePools`.
    @available(*, deprecated)
    func listAwsNodePools(request: ListAwsNodePoolsRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.ListAwsNodePoolsResponse

    /// See `AwsClustersClient.listAwsNodePools`.
    @available(*, deprecated)
    func listAwsNodePools(
      byItem: ListAwsNodePoolsRequest
    ) throws -> any AsyncSequence<AwsNodePool, Swift.Error>

    /// See `AwsClustersClient.listAwsNodePools`.
    @available(*, deprecated)
    func listAwsNodePools(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AwsNodePool, Swift.Error>

    /// See `AwsClustersClient.deleteAwsNodePool`.
    @available(*, deprecated)
    func deleteAwsNodePool(request: DeleteAwsNodePoolRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.deleteAwsNodePool`.
    @available(*, deprecated)
    func deleteAwsNodePool(withPolling: DeleteAwsNodePoolRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `AwsClustersClient.deleteAwsNodePool`.
    @available(*, deprecated)
    func deleteAwsNodePool(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AwsClustersClient.getAwsOpenIdConfig`.
    @available(*, deprecated)
    func getAwsOpenIdConfig(request: GetAwsOpenIdConfigRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.AwsOpenIdConfig

    /// See `AwsClustersClient.getAwsJsonWebKeys`.
    @available(*, deprecated)
    func getAwsJsonWebKeys(request: GetAwsJsonWebKeysRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.AwsJsonWebKeys

    /// See `AwsClustersClient.getAwsServerConfig`.
    @available(*, deprecated)
    func getAwsServerConfig(request: GetAwsServerConfigRequest) async throws
      -> GoogleCloudGKEMultiCloudV1.AwsServerConfig

    /// See `AwsClustersClient.getAwsServerConfig`.
    @available(*, deprecated)
    func getAwsServerConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsServerConfig

    /// See `AwsClustersClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AwsClustersClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AwsClustersClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AwsClustersClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `AwsClustersClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AwsClustersClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `AwsClustersClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AwsClustersClient.createAwsCluster`.
    @available(*, deprecated)
    func createAwsCluster(
      request: CreateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.createAwsCluster`.
    @available(*, deprecated)
    func createAwsCluster(
      withPolling: CreateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster>

    /// See `AwsClustersClient.updateAwsCluster`.
    @available(*, deprecated)
    func updateAwsCluster(
      request: UpdateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.updateAwsCluster`.
    @available(*, deprecated)
    func updateAwsCluster(
      withPolling: UpdateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster>

    /// See `AwsClustersClient.getAwsCluster`.
    @available(*, deprecated)
    func getAwsCluster(
      request: GetAwsClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsCluster

    /// See `AwsClustersClient.listAwsClusters`.
    @available(*, deprecated)
    func listAwsClusters(
      request: ListAwsClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsClustersResponse

    /// See `AwsClustersClient.listAwsClusters`.
    @available(*, deprecated)
    func listAwsClusters(
      byItem: ListAwsClustersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AwsCluster, Swift.Error>

    /// See `AwsClustersClient.deleteAwsCluster`.
    @available(*, deprecated)
    func deleteAwsCluster(
      request: DeleteAwsClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.deleteAwsCluster`.
    @available(*, deprecated)
    func deleteAwsCluster(
      withPolling: DeleteAwsClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AwsClustersClient.generateAwsClusterAgentToken`.
    @available(*, deprecated)
    func generateAwsClusterAgentToken(
      request: GenerateAwsClusterAgentTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAwsClusterAgentTokenResponse

    /// See `AwsClustersClient.generateAwsAccessToken`.
    @available(*, deprecated)
    func generateAwsAccessToken(
      request: GenerateAwsAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAwsAccessTokenResponse

    /// See `AwsClustersClient.createAwsNodePool`.
    @available(*, deprecated)
    func createAwsNodePool(
      request: CreateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.createAwsNodePool`.
    @available(*, deprecated)
    func createAwsNodePool(
      withPolling: CreateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.updateAwsNodePool`.
    @available(*, deprecated)
    func updateAwsNodePool(
      request: UpdateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.updateAwsNodePool`.
    @available(*, deprecated)
    func updateAwsNodePool(
      withPolling: UpdateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.rollbackAwsNodePoolUpdate`.
    @available(*, deprecated)
    func rollbackAwsNodePoolUpdate(
      request: RollbackAwsNodePoolUpdateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.rollbackAwsNodePoolUpdate`.
    @available(*, deprecated)
    func rollbackAwsNodePoolUpdate(
      withPolling: RollbackAwsNodePoolUpdateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool>

    /// See `AwsClustersClient.getAwsNodePool`.
    @available(*, deprecated)
    func getAwsNodePool(
      request: GetAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsNodePool

    /// See `AwsClustersClient.listAwsNodePools`.
    @available(*, deprecated)
    func listAwsNodePools(
      request: ListAwsNodePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsNodePoolsResponse

    /// See `AwsClustersClient.listAwsNodePools`.
    @available(*, deprecated)
    func listAwsNodePools(
      byItem: ListAwsNodePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AwsNodePool, Swift.Error>

    /// See `AwsClustersClient.deleteAwsNodePool`.
    @available(*, deprecated)
    func deleteAwsNodePool(
      request: DeleteAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AwsClustersClient.deleteAwsNodePool`.
    @available(*, deprecated)
    func deleteAwsNodePool(
      withPolling: DeleteAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AwsClustersClient.getAwsOpenIdConfig`.
    @available(*, deprecated)
    func getAwsOpenIdConfig(
      request: GetAwsOpenIdConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsOpenIdConfig

    /// See `AwsClustersClient.getAwsJsonWebKeys`.
    @available(*, deprecated)
    func getAwsJsonWebKeys(
      request: GetAwsJsonWebKeysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsJsonWebKeys

    /// See `AwsClustersClient.getAwsServerConfig`.
    @available(*, deprecated)
    func getAwsServerConfig(
      request: GetAwsServerConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGKEMultiCloudV1.AwsServerConfig

    /// See `AwsClustersClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AwsClustersClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AwsClustersClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AwsClustersClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
@available(*, deprecated)
extension Clients.AwsClustersProtocol {
  @available(*, deprecated)
  public func createAwsCluster(request: CreateAwsClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAwsCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAwsCluster(
    request: CreateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAwsCluster(withPolling: CreateAwsClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AwsCluster>
  {
    try await self.createAwsCluster(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func createAwsCluster(
    withPolling: CreateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func createAwsCluster(
    parent: Swift.String,
    awsCluster: AwsCluster?,
    awsClusterId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster> {
    let request = CreateAwsClusterRequest().with {
      $0.parent = parent
      $0.awsCluster = awsCluster
      $0.awsClusterId = awsClusterId
    }
    return try await self.createAwsCluster(withPolling: request)
  }

  @available(*, deprecated)
  public func updateAwsCluster(request: UpdateAwsClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAwsCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateAwsCluster(
    request: UpdateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateAwsCluster(withPolling: UpdateAwsClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AwsCluster>
  {
    try await self.updateAwsCluster(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func updateAwsCluster(
    withPolling: UpdateAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func updateAwsCluster(
    awsCluster: AwsCluster?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsCluster> {
    let request = UpdateAwsClusterRequest().with {
      $0.awsCluster = awsCluster
      $0.updateMask = updateMask
    }
    return try await self.updateAwsCluster(withPolling: request)
  }

  @available(*, deprecated)
  public func getAwsCluster(request: GetAwsClusterRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AwsCluster
  {
    try await self.getAwsCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAwsCluster(
    request: GetAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsCluster {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAwsCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsCluster {
    let request = GetAwsClusterRequest().with {
      $0.name = name
    }
    return try await self.getAwsCluster(request: request)
  }

  @available(*, deprecated)
  public func listAwsClusters(request: ListAwsClustersRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.ListAwsClustersResponse
  {
    try await self.listAwsClusters(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listAwsClusters(
    request: ListAwsClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsClustersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listAwsClusters(
    byItem: ListAwsClustersRequest
  ) throws -> any AsyncSequence<AwsCluster, Swift.Error> {
    try self.listAwsClusters(byItem: byItem, options: .init())
  }

  @available(*, deprecated)
  public func listAwsClusters(
    byItem: ListAwsClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AwsCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsClustersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  @available(*, deprecated)
  public func listAwsClusters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AwsCluster, Swift.Error> {
    let request = ListAwsClustersRequest().with {
      $0.parent = parent
    }
    return try self.listAwsClusters(byItem: request)
  }

  @available(*, deprecated)
  public func deleteAwsCluster(request: DeleteAwsClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAwsCluster(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAwsCluster(
    request: DeleteAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAwsCluster(withPolling: DeleteAwsClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAwsCluster(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func deleteAwsCluster(
    withPolling: DeleteAwsClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func deleteAwsCluster(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteAwsClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteAwsCluster(withPolling: request)
  }

  @available(*, deprecated)
  public func generateAwsClusterAgentToken(request: GenerateAwsClusterAgentTokenRequest)
    async throws -> GoogleCloudGKEMultiCloudV1.GenerateAwsClusterAgentTokenResponse
  {
    try await self.generateAwsClusterAgentToken(request: request, options: .init())
  }

  @available(*, deprecated)
  public func generateAwsClusterAgentToken(
    request: GenerateAwsClusterAgentTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAwsClusterAgentTokenResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func generateAwsAccessToken(request: GenerateAwsAccessTokenRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.GenerateAwsAccessTokenResponse
  {
    try await self.generateAwsAccessToken(request: request, options: .init())
  }

  @available(*, deprecated)
  public func generateAwsAccessToken(
    request: GenerateAwsAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.GenerateAwsAccessTokenResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAwsNodePool(request: CreateAwsNodePoolRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAwsNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createAwsNodePool(
    request: CreateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createAwsNodePool(withPolling: CreateAwsNodePoolRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AwsNodePool>
  {
    try await self.createAwsNodePool(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func createAwsNodePool(
    withPolling: CreateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func createAwsNodePool(
    parent: Swift.String,
    awsNodePool: AwsNodePool?,
    awsNodePoolId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let request = CreateAwsNodePoolRequest().with {
      $0.parent = parent
      $0.awsNodePool = awsNodePool
      $0.awsNodePoolId = awsNodePoolId
    }
    return try await self.createAwsNodePool(withPolling: request)
  }

  @available(*, deprecated)
  public func updateAwsNodePool(request: UpdateAwsNodePoolRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAwsNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateAwsNodePool(
    request: UpdateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateAwsNodePool(withPolling: UpdateAwsNodePoolRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AwsNodePool>
  {
    try await self.updateAwsNodePool(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func updateAwsNodePool(
    withPolling: UpdateAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func updateAwsNodePool(
    awsNodePool: AwsNodePool?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let request = UpdateAwsNodePoolRequest().with {
      $0.awsNodePool = awsNodePool
      $0.updateMask = updateMask
    }
    return try await self.updateAwsNodePool(withPolling: request)
  }

  @available(*, deprecated)
  public func rollbackAwsNodePoolUpdate(request: RollbackAwsNodePoolUpdateRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.rollbackAwsNodePoolUpdate(request: request, options: .init())
  }

  @available(*, deprecated)
  public func rollbackAwsNodePoolUpdate(
    request: RollbackAwsNodePoolUpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func rollbackAwsNodePoolUpdate(withPolling: RollbackAwsNodePoolUpdateRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AwsNodePool>
  {
    try await self.rollbackAwsNodePoolUpdate(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func rollbackAwsNodePoolUpdate(
    withPolling: RollbackAwsNodePoolUpdateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AwsNodePool>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func rollbackAwsNodePoolUpdate(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AwsNodePool> {
    let request = RollbackAwsNodePoolUpdateRequest().with {
      $0.name = name
    }
    return try await self.rollbackAwsNodePoolUpdate(withPolling: request)
  }

  @available(*, deprecated)
  public func getAwsNodePool(request: GetAwsNodePoolRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AwsNodePool
  {
    try await self.getAwsNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAwsNodePool(
    request: GetAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsNodePool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAwsNodePool(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsNodePool {
    let request = GetAwsNodePoolRequest().with {
      $0.name = name
    }
    return try await self.getAwsNodePool(request: request)
  }

  @available(*, deprecated)
  public func listAwsNodePools(request: ListAwsNodePoolsRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.ListAwsNodePoolsResponse
  {
    try await self.listAwsNodePools(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listAwsNodePools(
    request: ListAwsNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsNodePoolsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listAwsNodePools(
    byItem: ListAwsNodePoolsRequest
  ) throws -> any AsyncSequence<AwsNodePool, Swift.Error> {
    try self.listAwsNodePools(byItem: byItem, options: .init())
  }

  @available(*, deprecated)
  public func listAwsNodePools(
    byItem: ListAwsNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AwsNodePool, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudGKEMultiCloudV1.ListAwsNodePoolsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  @available(*, deprecated)
  public func listAwsNodePools(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AwsNodePool, Swift.Error> {
    let request = ListAwsNodePoolsRequest().with {
      $0.parent = parent
    }
    return try self.listAwsNodePools(byItem: request)
  }

  @available(*, deprecated)
  public func deleteAwsNodePool(request: DeleteAwsNodePoolRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAwsNodePool(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteAwsNodePool(
    request: DeleteAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteAwsNodePool(withPolling: DeleteAwsNodePoolRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAwsNodePool(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func deleteAwsNodePool(
    withPolling: DeleteAwsNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func deleteAwsNodePool(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteAwsNodePoolRequest().with {
      $0.name = name
    }
    return try await self.deleteAwsNodePool(withPolling: request)
  }

  @available(*, deprecated)
  public func getAwsOpenIdConfig(request: GetAwsOpenIdConfigRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AwsOpenIdConfig
  {
    try await self.getAwsOpenIdConfig(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAwsOpenIdConfig(
    request: GetAwsOpenIdConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsOpenIdConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAwsJsonWebKeys(request: GetAwsJsonWebKeysRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AwsJsonWebKeys
  {
    try await self.getAwsJsonWebKeys(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAwsJsonWebKeys(
    request: GetAwsJsonWebKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsJsonWebKeys {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAwsServerConfig(request: GetAwsServerConfigRequest) async throws
    -> GoogleCloudGKEMultiCloudV1.AwsServerConfig
  {
    try await self.getAwsServerConfig(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getAwsServerConfig(
    request: GetAwsServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsServerConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getAwsServerConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudGKEMultiCloudV1.AwsServerConfig {
    let request = GetAwsServerConfigRequest().with {
      $0.name = name
    }
    return try await self.getAwsServerConfig(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
