// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// `AzureClient` resources hold client authentication information needed by the
/// Anthos Multi-Cloud API to manage Azure resources on your Azure subscription.
///
/// When an [AzureCluster][google.cloud.gkemulticloud.v1.AzureCluster] is
/// created, an `AzureClient` resource needs to be provided and all operations on
/// Azure resources associated to that cluster will authenticate to Azure
/// services using the given client.
///
/// `AzureClient` resources are immutable and cannot be modified upon creation.
///
/// Each `AzureClient` resource is bound to a single Azure Active Directory
/// Application and tenant.
///
/// [google.cloud.gkemulticloud.v1.AzureCluster]: <doc:AzureCluster>
@available(*, deprecated)
public struct AzureClient: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of this resource.
  ///
  /// `AzureClient` resource names are formatted as
  /// `projects/<project-number>/locations/<region>/azureClients/<client-id>`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud resource names.
  public var name: Swift.String = Swift.String()

  /// Required. The Azure Active Directory Tenant ID.
  public var tenantId: Swift.String = Swift.String()

  /// Required. The Azure Active Directory Application ID.
  public var applicationId: Swift.String = Swift.String()

  /// Output only. If set, there are currently pending changes to the client.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. Annotations on the resource.
  ///
  /// This field has the same restrictions as Kubernetes annotations.
  /// The total size of all keys and values combined is limited to 256k.
  /// Keys can have 2 segments: prefix (optional) and name (required),
  /// separated by a slash (/).
  /// Prefix must be a DNS subdomain.
  /// Name must be 63 characters or less, begin and end with alphanumerics,
  /// with dashes (-), underscores (_), dots (.), and alphanumerics between.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The PEM encoded x509 certificate.
  public var pemCertificate: Swift.String = Swift.String()

  /// Output only. A globally unique identifier for the client.
  public var uid: Swift.String = Swift.String()

  /// Output only. The time at which this resource was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time at which this client was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `AzureClient`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureClient().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureClient"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
