// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// AzureServerConfig contains information about a Google Cloud location, such as
/// supported Azure regions and Kubernetes versions.
@available(*, deprecated)
public struct AzureServerConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The `AzureServerConfig` resource name.
  ///
  /// `AzureServerConfig` names are formatted as
  /// `projects/<project-number>/locations/<region>/azureServerConfig`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud Platform resource names.
  public var name: Swift.String = Swift.String()

  /// List of all released Kubernetes versions, including ones which are end of
  /// life and can no longer be used.  Filter by the `enabled`
  /// property to limit to currently available versions.
  /// Valid versions supported for both create and update operations
  public var validVersions: [AzureK8sVersionInfo] = []

  /// The list of supported Azure regions.
  public var supportedAzureRegions: [Swift.String] = []

  /// Initialize a new instance of `AzureServerConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureServerConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureServerConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
