// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// AzureControlPlane represents the control plane configurations.
@available(*, deprecated)
public struct AzureControlPlane: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The Kubernetes version to run on control plane replicas
  /// (e.g. `1.19.10-gke.1000`).
  ///
  /// You can list all supported versions on a given Google Cloud region by
  /// calling
  /// [GetAzureServerConfig][google.cloud.gkemulticloud.v1.AzureClusters.GetAzureServerConfig].
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClusters.GetAzureServerConfig]: <doc:AzureClustersClient/getAzureServerConfig(request:options:)>
  public var version: Swift.String = Swift.String()

  /// Optional. The ARM ID of the default subnet for the control plane. The
  /// control plane VMs are deployed in this subnet, unless
  /// `AzureControlPlane.replica_placements` is specified. This subnet will also
  /// be used as default for `AzureControlPlane.endpoint_subnet_id` if
  /// `AzureControlPlane.endpoint_subnet_id` is not specified. Similarly it will
  /// be used as default for
  /// `AzureClusterNetworking.service_load_balancer_subnet_id`.
  ///
  /// Example:
  /// `/subscriptions/<subscription-id>/resourceGroups/<resource-group-id>/providers/Microsoft.Network/virtualNetworks/<vnet-id>/subnets/default`.
  public var subnetId: Swift.String = Swift.String()

  /// Optional. The Azure VM size name. Example: `Standard_DS2_v2`.
  ///
  /// For available VM sizes, see
  /// https://docs.microsoft.com/en-us/azure/virtual-machines/vm-naming-conventions.
  ///
  /// When unspecified, it defaults to `Standard_DS2_v2`.
  public var vmSize: Swift.String = Swift.String()

  /// Required. SSH configuration for how to access the underlying control plane
  /// machines.
  public var sshConfig: AzureSshConfig? = nil

  /// Optional. Configuration related to the root volume provisioned for each
  /// control plane replica.
  ///
  /// When unspecified, it defaults to 32-GiB Azure Disk.
  public var rootVolume: AzureDiskTemplate? = nil

  /// Optional. Configuration related to the main volume provisioned for each
  /// control plane replica.
  /// The main volume is in charge of storing all of the cluster's etcd state.
  ///
  /// When unspecified, it defaults to a 8-GiB Azure Disk.
  public var mainVolume: AzureDiskTemplate? = nil

  /// Optional. Configuration related to application-layer secrets encryption.
  public var databaseEncryption: AzureDatabaseEncryption? = nil

  /// Optional. Proxy configuration for outbound HTTP(S) traffic.
  public var proxyConfig: AzureProxyConfig? = nil

  /// Optional. Configuration related to vm config encryption.
  public var configEncryption: AzureConfigEncryption? = nil

  /// Optional. A set of tags to apply to all underlying control plane Azure
  /// resources.
  public var tags: [Swift.String: Swift.String] = [:]

  /// Optional. Configuration for where to place the control plane replicas.
  ///
  /// Up to three replica placement instances can be specified. If
  /// replica_placements is set, the replica placement instances will be applied
  /// to the three control plane replicas as evenly as possible.
  public var replicaPlacements: [ReplicaPlacement] = []

  /// Optional. The ARM ID of the subnet where the control plane load balancer is
  /// deployed. When unspecified, it defaults to AzureControlPlane.subnet_id.
  ///
  /// Example:
  /// "/subscriptions/d00494d6-6f3c-4280-bbb2-899e163d1d30/resourceGroups/anthos_cluster_gkeust4/providers/Microsoft.Network/virtualNetworks/gke-vnet-gkeust4/subnets/subnetid123"
  public var endpointSubnetId: Swift.String = Swift.String()

  /// Initialize a new instance of `AzureControlPlane`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureControlPlane().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureControlPlane"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
