// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Parameters that describe the configuration of all node machines
/// on a given node pool.
@available(*, deprecated)
public struct AzureNodeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The Azure VM size name. Example: `Standard_DS2_v2`.
  ///
  /// See [Supported VM
  /// sizes](/anthos/clusters/docs/azure/reference/supported-vms) for options.
  ///
  /// When unspecified, it defaults to `Standard_DS2_v2`.
  public var vmSize: Swift.String = Swift.String()

  /// Optional. Configuration related to the root volume provisioned for each
  /// node pool machine.
  ///
  /// When unspecified, it defaults to a 32-GiB Azure Disk.
  public var rootVolume: AzureDiskTemplate? = nil

  /// Optional. A set of tags to apply to all underlying Azure resources for this
  /// node pool. This currently only includes Virtual Machine Scale Sets.
  ///
  /// Specify at most 50 pairs containing alphanumerics, spaces, and symbols
  /// (.+-=_:@/). Keys can be up to 127 Unicode characters. Values can be up to
  /// 255 Unicode characters.
  public var tags: [Swift.String: Swift.String] = [:]

  /// Optional. The OS image type to use on node pool instances.
  /// Can be unspecified, or have a value of `ubuntu`.
  ///
  /// When unspecified, it defaults to `ubuntu`.
  public var imageType: Swift.String = Swift.String()

  /// Required. SSH configuration for how to access the node pool machines.
  public var sshConfig: AzureSshConfig? = nil

  /// Optional. Proxy configuration for outbound HTTP(S) traffic.
  public var proxyConfig: AzureProxyConfig? = nil

  /// Optional. Configuration related to vm config encryption.
  public var configEncryption: AzureConfigEncryption? = nil

  /// Optional. The initial taints assigned to nodes of this node pool.
  public var taints: [NodeTaint] = []

  /// Optional. The initial labels assigned to nodes of this node pool. An object
  /// containing a list of "key": value pairs. Example: { "name": "wrench",
  /// "mass": "1.3kg", "count": "3" }.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `AzureNodeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AzureNodeConfig().with { $0.vmSize = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.AzureNodeConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
