// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for `AzureClusters.CreateAzureClient` method.
@available(*, deprecated)
public struct CreateAzureClientRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent location where this
  /// [AzureClient][google.cloud.gkemulticloud.v1.AzureClient] resource will be
  /// created.
  ///
  /// Location names are formatted as `projects/<project-id>/locations/<region>`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud resource names.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  public var parent: Swift.String = Swift.String()

  /// Required. The specification of the
  /// [AzureClient][google.cloud.gkemulticloud.v1.AzureClient] to create.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  public var azureClient: AzureClient? = nil

  /// Required. A client provided ID the resource. Must be unique within the
  /// parent resource.
  ///
  /// The provided ID will be part of the
  /// [AzureClient][google.cloud.gkemulticloud.v1.AzureClient] resource name
  /// formatted as
  /// `projects/<project-id>/locations/<region>/azureClients/<client-id>`.
  ///
  /// Valid characters are `/[a-z][0-9]-/`. Cannot be longer than 63 characters.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  public var azureClientId: Swift.String = Swift.String()

  /// If set, only validate the request, but do not actually create the client.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateAzureClientRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAzureClientRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.CreateAzureClientRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
