// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct GenerateAttachedClusterAgentTokenRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required.
  public var attachedCluster: Swift.String = Swift.String()

  /// Required.
  public var subjectToken: Swift.String = Swift.String()

  /// Required.
  public var subjectTokenType: Swift.String = Swift.String()

  /// Required.
  public var version: Swift.String = Swift.String()

  /// Optional.
  public var grantType: Swift.String = Swift.String()

  /// Optional.
  public var audience: Swift.String = Swift.String()

  /// Optional.
  public var scope: Swift.String = Swift.String()

  /// Optional.
  public var requestedTokenType: Swift.String = Swift.String()

  /// Optional.
  public var options: Swift.String = Swift.String()

  /// Initialize a new instance of `GenerateAttachedClusterAgentTokenRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateAttachedClusterAgentTokenRequest().with { $0.attachedCluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.gkemulticloud.v1.GenerateAttachedClusterAgentTokenRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
