// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for `AttachedClusters.GenerateAttachedClusterInstallManifest`
/// method.
public struct GenerateAttachedClusterInstallManifestRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. The parent location where this
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// will be created.
  ///
  /// Location names are formatted as `projects/<project-id>/locations/<region>`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud resource names.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  public var parent: Swift.String = Swift.String()

  /// Required. A client provided ID of the resource. Must be unique within the
  /// parent resource.
  ///
  /// The provided ID will be part of the
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// name formatted as
  /// `projects/<project-id>/locations/<region>/attachedClusters/<cluster-id>`.
  ///
  /// Valid characters are `/[a-z][0-9]-/`. Cannot be longer than 63 characters.
  ///
  /// When generating an install manifest for importing an existing Membership
  /// resource, the attached_cluster_id field must be the Membership id.
  ///
  /// Membership names are formatted as
  /// `projects/<project-id>/locations/<region>/memberships/<membership-id>`.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  public var attachedClusterId: Swift.String = Swift.String()

  /// Required. The platform version for the cluster (e.g. `1.19.0-gke.1000`).
  ///
  /// You can list all supported versions on a given Google Cloud region by
  /// calling
  /// [GetAttachedServerConfig][google.cloud.gkemulticloud.v1.AttachedClusters.GetAttachedServerConfig].
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedClusters.GetAttachedServerConfig]: <doc:AttachedClusters/getAttachedServerConfig(request:)>
  public var platformVersion: Swift.String = Swift.String()

  /// Optional. Proxy configuration for outbound HTTP(S) traffic.
  public var proxyConfig: AttachedProxyConfig? = nil

  /// Initialize a new instance of `GenerateAttachedClusterInstallManifestRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateAttachedClusterInstallManifestRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.gkemulticloud.v1.GenerateAttachedClusterInstallManifestRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
