// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for `AzureClusters.GetAzureClient` method.
@available(*, deprecated)
public struct GetAzureClientRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the
  /// [AzureClient][google.cloud.gkemulticloud.v1.AzureClient] resource to
  /// describe.
  ///
  /// [AzureClient][google.cloud.gkemulticloud.v1.AzureClient] names are
  /// formatted as
  /// `projects/<project-id>/locations/<region>/azureClients/<client-id>`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud resource names.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureClient]: <doc:AzureClient>
  public var name: Swift.String = Swift.String()

  /// Initialize a new instance of `GetAzureClientRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GetAzureClientRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.GetAzureClientRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
