// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Response message for `AzureClusters.ListAzureNodePools` method.
@available(*, deprecated)
public struct ListAzureNodePoolsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// A list of [AzureNodePool][google.cloud.gkemulticloud.v1.AzureNodePool]
  /// resources in the specified `AzureCluster`.
  ///
  /// [google.cloud.gkemulticloud.v1.AzureNodePool]: <doc:AzureNodePool>
  public var azureNodePools: [AzureNodePool] = []

  /// Token to retrieve the next page of results, or empty if there are no more
  /// results in the list.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAzureNodePoolsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAzureNodePoolsResponse().with { $0.azureNodePools = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.ListAzureNodePoolsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [AzureNodePool] {
    return self.azureNodePools
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
