// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for `AwsClusters.ListAwsClusters` method.
@available(*, deprecated)
public struct ListAwsClustersRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent location which owns this collection of
  /// [AwsCluster][google.cloud.gkemulticloud.v1.AwsCluster] resources.
  ///
  /// Location names are formatted as `projects/<project-id>/locations/<region>`.
  ///
  /// See [Resource Names](https://cloud.google.com/apis/design/resource_names)
  /// for more details on Google Cloud Platform resource names.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsCluster]: <doc:AwsCluster>
  public var parent: Swift.String = Swift.String()

  /// The maximum number of items to return.
  ///
  /// If not specified, a default value of 50 will be used by the service.
  /// Regardless of the pageSize value, the response can include a partial list
  /// and a caller should only rely on response's
  /// [nextPageToken][google.cloud.gkemulticloud.v1.ListAwsClustersResponse.next_page_token]
  /// to determine if there are more instances left to be queried.
  ///
  /// [google.cloud.gkemulticloud.v1.ListAwsClustersResponse.next_page_token]: <doc:ListAwsClustersResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The `nextPageToken` value returned from a previous
  /// [awsClusters.list][google.cloud.gkemulticloud.v1.AwsClusters.ListAwsClusters]
  /// request, if any.
  ///
  /// [google.cloud.gkemulticloud.v1.AwsClusters.ListAwsClusters]: <doc:AwsClustersClient/listAwsClusters(request:options:)>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAwsClustersRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAwsClustersRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.ListAwsClustersRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
