// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Metadata about a long-running operation.
public struct OperationMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The time at which this operation was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which this operation was completed.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The name of the resource associated to this operation.
  public var target: Swift.String = Swift.String()

  /// Output only. Human-readable status of the operation, if any.
  public var statusDetail: Swift.String = Swift.String()

  /// Output only. Human-readable status of any error that occurred during the
  /// operation.
  public var errorDetail: Swift.String = Swift.String()

  /// Output only. The verb associated with the API method which triggered this
  /// operation. Possible values are "create", "delete", "update" and "import".
  public var verb: Swift.String = Swift.String()

  /// Output only. Identifies whether cancellation has been requested for the
  /// operation. Operations that have successfully been cancelled have
  /// [google.longrunning.Operation.error][google.longrunning.Operation.error]
  /// value with a [google.rpc.Status.code][google.rpc.Status.code] of 1,
  /// corresponding to `Code.CANCELLED`.
  ///
  /// [google.longrunning.Operation.error]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/error(_:)
  /// [google.rpc.Status.code]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/code
  public var requestedCancellation: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `OperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.OperationMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
