// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for `AttachedClusters.UpdateAttachedCluster` method.
public struct UpdateAttachedClusterRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster] resource
  /// to update.
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  public var attachedCluster: AttachedCluster? = nil

  /// If set, only validate the request, but do not actually update the cluster.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Required. Mask of fields to update. At least one path must be supplied in
  /// this field. The elements of the repeated paths field can only include these
  /// fields from
  /// [AttachedCluster][google.cloud.gkemulticloud.v1.AttachedCluster]:
  ///
  ///  *   `annotations`.
  ///  *   `authorization.admin_groups`.
  ///  *   `authorization.admin_users`.
  ///  *   `binary_authorization.evaluation_mode`.
  ///  *   `description`.
  ///  *   `logging_config.component_config.enable_components`.
  ///  *   `monitoring_config.managed_prometheus_config.enabled`.
  ///  *   `platform_version`.
  ///  *   `proxy_config.kubernetes_secret.name`.
  ///  *   `proxy_config.kubernetes_secret.namespace`.
  ///  *   `security_posture_config.vulnerability_mode`
  ///  *   `monitoring_config.cloud_monitoring_config.enabled`
  ///
  /// [google.cloud.gkemulticloud.v1.AttachedCluster]: <doc:AttachedCluster>
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateAttachedClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateAttachedClusterRequest().with { $0.attachedCluster = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkemulticloud.v1.UpdateAttachedClusterRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
